[build]
  command = "npm run build"
  publish = ".next"
  base = "frontend"

[build.environment]
  NEXT_USE_LIBUV_NODEJS = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
